--uncomment to make any changes
--change type for rooms
--ALTER TYPE "room_listing_roomType" ADD VALUE 'Single Room' AFTER 'living room';
--ALTER TYPE "room_listing_roomType" ADD VALUE 'Double Room' AFTER 'Single Room';
--ALTER TYPE "room_listing_roomType" ADD VALUE 'Entire Apt' AFTER 'Double Room';
--ALTER TYPE "room_listing_roomType" ADD VALUE 'Living Room' AFTER 'Entire Apt';
--ALTER TYPE "room_listing_roomType" ADD VALUE 'Entire House' AFTER 'Living Room';
--ALTER TYPE "room_listing_roomType" ADD VALUE 'Entire Apartment' AFTER 'Entire House';
--ALTER TYPE "room_listing_roomType" ADD VALUE 'Entire Apt' AFTER 'Enitre Apt';

--change type for lookings
--ALTER TYPE "looking_roomType" ADD VALUE 'Single Room' AFTER 'living room';
--ALTER TYPE "looking_roomType" ADD VALUE 'Double Room' AFTER 'Single Room';
--ALTER TYPE "looking_roomType" ADD VALUE 'Entire Apartment' AFTER 'Double Room';
--ALTER TYPE "looking_roomType" ADD VALUE 'Living Room' AFTER 'Entire Apartment';
--ALTER TYPE "looking_roomType" ADD VALUE 'Entire House' AFTER 'Living Room';
