/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'university-custom.js' file in this directory.
2. Copy the code below and paste it into 'university-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./university.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("univcalquarterUniversities").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.university",
    options: {
        tableName: "university",
        //schema: "rented",
        timestamps: true
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "university_pkey"
        },
        "name": {
            type: Seq.STRING(255),
            field: "name",
            allowNull: false
        },
        "academicYearType": {
            type: Seq.CHAR(255),
            field: "academicYearType"
        },
        "streetNumeric": {
            type: Seq.INTEGER,
            field: "streetNumeric",
            allowNull: false
        },
        "streetAddress": {
            type: Seq.STRING(255),
            field: "streetAddress",
            allowNull: false
        },
        "latitude": {
            type: Seq.BIGINT,
            field: "latitude"
        },
        "longitude": {
            type: Seq.BIGINT,
            field: "longitude"
        },
        "apt": {
            type: Seq.STRING(6),
            field: "apt"
        },
        "city": {
            type: Seq.STRING(30),
            field: "city",
            allowNull: false
        },
        "state": {
            type: Seq.STRING(2),
            field: "state",
            allowNull: false
        },
        "zip": {
            type: Seq.BIGINT,
            field: "zip",
            allowNull: false
        },
        "startDate": {
            type: Seq.DATE,
            field: "startDate",
            allowNull: false
        },
        "endDate": {
            type: Seq.DATE,
            field: "endDate"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "hasMany",
        model: "rented.universityCalenderQuater",
        schema: "rented",
        table: "university_calender_quater",
        source: "generator",
        details: {
            as: "univcalquarterUniversities",
            foreignKey: "universityId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "rented.universityCalenderSemester",
        schema: "rented",
        table: "university_calender_semester",
        source: "generator",
        details: {
            as: "univcalsemesterUniversities",
            foreignKey: "universityId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
