/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'property_listing-custom.js' file in this directory.
2. Copy the code below and paste it into 'property_listing-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./property_listing.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedPropertyId").onDelete = 'CASCADE';
util.getAttribute("propertyId").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.propertyListing",
    options: {
        tableName: "property_listing",
        //schema: "rented",
        timestamps: true
    },
    attributes: {
        "propertyId": {
            type: Seq.BIGINT,
            field: "propertyId",
            allowNull: false,
            references: "property",
            referencesKey: "propertyId"
        },
        "monthlyPrice": {
            type: Seq.FLOAT(53),
            field: "monthlyPrice",
            allowNull: false
        },
        "securityDeposit": {
            type: Seq.FLOAT(53),
            field: "securityDeposit"
        },
        "petDeposit": {
            type: Seq.FLOAT(53),
            field: "petDeposit"
        },
        "availableMoveIn": {
            type: Seq.DATE,
            field: "availableMoveIn",
            allowNull: false
        },
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "property_listing_pkey"
        },
        "leaseEndDate": {
            type: Seq.DATE,
            field: "leaseEndDate"
        },
        "leaseLength": {
            type: Seq.BIGINT,
            field: "leaseLength",
            allowNull: false
        },
        "leaseLengthUnit": {
            type: Seq.CHAR(255),
            field: "leaseLengthUnit",
            allowNull: false
        },
        "leaseType": {
            type: Seq.CHAR(255),
            field: "leaseType",
            allowNull: false
        },
        "gender": {
            type: Seq.CHAR(255),
            field: "gender",
            allowNull: false
        },
        "totalUtilityCost": {
            type: Seq.INTEGER,
            field: "totalUtilityCost",
            allowNull: false
        },
        "roomType": {
            type: Seq.CHAR(255),
            field: "roomType",
            allowNull: false
        },
        "sharedBathroom": {
            type: Seq.BOOLEAN,
            field: "sharedBathroom"
        },
        "numRoomates": {
            type: Seq.BIGINT,
            field: "numRoomates",
            allowNull: false
        },
        "furnished": {
            type: Seq.BOOLEAN,
            field: "furnished"
        },
        "parkingAvailable": {
            type: Seq.BOOLEAN,
            field: "parkingAvailable"
        },
        "smokingAllowed": {
            type: Seq.BOOLEAN,
            field: "smokingAllowed"
        },
        "description": {
            type: Seq.STRING(255),
            field: "description"
        },
        "status": {
            type: Seq.CHAR(255),
            field: "status"
        },
        "contactPhone": {
            type: Seq.INTEGER,
            field: "contactPhone"
        },
        "contactEmail": {
            type: Seq.STRING(45),
            field: "contactEmail",
            allowNull: false
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.property",
        schema: "rented",
        table: "property",
        source: "generator",
        details: {
            as: "relatedPropertyId",
            foreignKey: "propertyId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
