/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'university_calender_quater-custom.js' file in this directory.
2. Copy the code below and paste it into 'university_calender_quater-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./university_calender_quater.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUniversityId").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.universityCalenderQuater",
    options: {
        tableName: "university_calender_quater",
        schema: "rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "university_calender_quater_pkey"
        },
        "universityId": {
            type: Seq.BIGINT,
            field: "universityId",
            allowNull: false,
            references: "university",
            referencesKey: "universityId"
        },
        "year": {
            type: Seq.INTEGER,
            field: "year",
            allowNull: false
        },
        "fallQuaterStartDate": {
            type: Seq.DATE,
            field: "fallQuaterStartDate",
            allowNull: false
        },
        "fallQuaterEndDate": {
            type: Seq.DATE,
            field: "fallQuaterEndDate",
            allowNull: false
        },
        "winterQuaterStartDate": {
            type: Seq.DATE,
            field: "winterQuaterStartDate",
            allowNull: false
        },
        "winterQuaterEndDate": {
            type: Seq.DATE,
            field: "winterQuaterEndDate",
            allowNull: false
        },
        "springQuaterStartDate": {
            type: Seq.DATE,
            field: "springQuaterStartDate",
            allowNull: false
        },
        "springQuaterEndDate": {
            type: Seq.DATE,
            field: "springQuaterEndDate",
            allowNull: false
        },
        "summerQuaterStartDate": {
            type: Seq.DATE,
            field: "summerQuaterStartDate",
            allowNull: false
        },
        "summerQuaterEndDate": {
            type: Seq.DATE,
            field: "summerQuaterEndDate",
            allowNull: false
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.university",
        schema: "rented",
        table: "university",
        source: "generator",
        details: {
            as: "relatedUniversityId",
            foreignKey: "universityId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};