/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'property_owner-custom.js' file in this directory.
2. Copy the code below and paste it into 'property_owner-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./property_owner.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedOwnerId").onDelete = 'CASCADE'; 
util.getAttribute("propertyOwnershipId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.propertyOwner",
    options: {
        tableName: "property_owner",
        schema: "rented",
        timestamps: false
    },
    attributes: {
        "propertyOwnershipId": {
            type: Seq.BIGINT,
            field: "propertyOwnershipId",
            primaryKey: true,
            allowNull: false,
            unique: "property_owner_pkey"
        },
        "ownerId": {
            type: Seq.BIGINT,
            field: "ownerId",
            primaryKey: true,
            allowNull: false,
            unique: "property_owner_pkey",
            references: "rented_user",
            referencesKey: "ownerId"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedOwnerId",
            foreignKey: "ownerId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};