/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'user_financial-custom.js' file in this directory.
2. Copy the code below and paste it into 'user_financial-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./user_financial.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUserid").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.userFinancial",
    options: {
        tableName: "user_financial",
        //schema: "Rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "user_financial_pkey"
        },
        "userid": {
            type: Seq.INTEGER,
            field: "userid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "userid"
        },
        "startdate": {
            type: Seq.DATE,
            field: "startdate",
            allowNull: false
        },
        "enddate": {
            type: Seq.DATE,
            field: "enddate"
        },
        "individualannualincom": {
            type: Seq.INTEGER,
            field: "individualannualincom"
        },
        "householdannualincome": {
            type: Seq.INTEGER,
            field: "householdannualincome"
        },
        "spouseannualincome": {
            type: Seq.INTEGER,
            field: "spouseannualincome"
        },
        "incomeproof": {
            type: Seq.STRING(255),
            field: "incomeproof"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserid",
            foreignKey: "userid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
