/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'apartment_complex-custom.js' file in this directory.
2. Copy the code below and paste it into 'apartment_complex-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./apartment_complex.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("floorPlanComplexidFkeys").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.apartmentComplex",
    options: {
        tableName: "apartment_complex",
        //schema: "Rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "apartment_complex_pkey"
        },
        "name": {
            type: Seq.STRING(255),
            field: "name",
            allowNull: false
        },
        "streetnumeric": {
            type: Seq.INTEGER,
            field: "streetnumeric",
            allowNull: false
        },
        "streetaddress": {
            type: Seq.STRING(255),
            field: "streetaddress",
            allowNull: false
        },
        "city": {
            type: Seq.STRING(30),
            field: "city",
            allowNull: false
        },
        "state": {
            type: Seq.STRING(2),
            field: "state",
            allowNull: false
        },
        "zip": {
            type: Seq.INTEGER,
            field: "zip",
            allowNull: false
        },
        "latitude": {
            type: Seq.DECIMAL(10, 8),
            field: "latitude"
        },
        "longitude": {
            type: Seq.DECIMAL(11, 8),
            field: "longitude"
        },
        "distancetouniv": {
            type: Seq.FLOAT(53),
            field: "distancetouniv"
        },
        "petsallowed": {
            type: Seq.INTEGER,
            field: "petsallowed",
            allowNull: false
        },
        "dogsallowed": {
            type: Seq.INTEGER,
            field: "dogsallowed",
            allowNull: false
        },
        "catsallowed": {
            type: Seq.INTEGER,
            field: "catsallowed",
            allowNull: false
        },
        "othersallowed": {
            type: Seq.INTEGER,
            field: "othersallowed",
            allowNull: false
        },
        "dogqtyallowed": {
            type: Seq.INTEGER,
            field: "dogqtyallowed"
        },
        "catqtyallowed": {
            type: Seq.INTEGER,
            field: "catqtyallowed"
        },
        "otherqtyallowed": {
            type: Seq.INTEGER,
            field: "otherqtyallowed"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "hasMany",
        model: "rented.apartmentComplexFloorPlan",
        schema: "Rented",
        table: "apartment_complex_floor_plan",
        source: "generator",
        details: {
            as: "floorPlanComplexidFkeys",
            foreignKey: "complexid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "rented.apartmentComplexImage",
        schema: "Rented",
        table: "apartment_complex_image",
        source: "generator",
        details: {
            as: "imageComplexidFkeys",
            foreignKey: "complexid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "rented.apartmentComplexTransportation",
        schema: "Rented",
        table: "apartment_complex_transportation",
        source: "generator",
        details: {
            as: "transportationComplexidFkeys",
            foreignKey: "complexid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
