/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'property_listing-custom.js' file in this directory.
2. Copy the code below and paste it into 'property_listing-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./property_listing.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("propertyImagesListingidFkeys").onDelete = 'CASCADE';
util.getAttribute("propertyid").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.propertyListing",
    options: {
        tableName: "property_listing",
        //schema: "Rented",
        timestamps: false
    },
    attributes: {
        "propertyid": {
            type: Seq.INTEGER,
            field: "propertyid",
            allowNull: false,
            references: "property",
            referencesKey: "propertyid"
        },
        "monthlyprice": {
            type: Seq.FLOAT(53),
            field: "monthlyprice",
            allowNull: false
        },
        "securitydeposit": {
            type: Seq.FLOAT(53),
            field: "securitydeposit"
        },
        "petdeposit": {
            type: Seq.FLOAT(53),
            field: "petdeposit"
        },
        "availablemovein": {
            type: Seq.DATE,
            field: "availablemovein",
            allowNull: false
        },
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "property_listing_pkey"
        },
        "leaseenddate": {
            type: Seq.DATE,
            field: "leaseenddate"
        },
        "leaselength": {
            type: Seq.INTEGER,
            field: "leaselength",
            allowNull: false
        },
        "leaselengthunit": {
            type: Seq.STRING(250),
            field: "leaselengthunit",
            allowNull: false
        },
        "leasetype": {
            type: Seq.STRING(250),
            field: "leasetype",
            allowNull: false
        },
        "gender": {
            type: Seq.STRING(250),
            field: "gender",
            allowNull: false
        },
        "totalutilitycost": {
            type: Seq.INTEGER,
            field: "totalutilitycost",
            allowNull: false
        },
        "roomtype": {
            type: Seq.STRING(250),
            field: "roomtype",
            allowNull: false
        },
        "sharedbathroom": {
            type: Seq.INTEGER,
            field: "sharedbathroom"
        },
        "numroomates": {
            type: Seq.INTEGER,
            field: "numroomates",
            allowNull: false
        },
        "furnished": {
            type: Seq.INTEGER,
            field: "furnished"
        },
        "parkingavailable": {
            type: Seq.INTEGER,
            field: "parkingavailable"
        },
        "smokingallowed": {
            type: Seq.INTEGER,
            field: "smokingallowed"
        },
        "description": {
            type: Seq.STRING(255),
            field: "description"
        },
        "status": {
            type: Seq.STRING(250),
            field: "status"
        },
        "contactphone": {
            type: Seq.INTEGER,
            field: "contactphone"
        },
        "contactemail": {
            type: Seq.STRING(45),
            field: "contactemail",
            allowNull: false
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "hasMany",
        model: "rented.propertyImages",
        schema: "Rented",
        table: "property_images",
        source: "generator",
        details: {
            as: "propertyImagesListingidFkeys",
            foreignKey: "listingid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rented.property",
        schema: "Rented",
        table: "property",
        source: "generator",
        details: {
            as: "relatedPropertyid",
            foreignKey: "propertyid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "rented.property",
        schema: "Rented",
        table: "property",
        source: "generator",
        details: {
            as: "relatedPropertyImagesListingidFkeyPropertyids",
            foreignKey: "listingid",
            otherKey: "propertyid",
            through: "property_images",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
