/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'university_calender_quater-custom.js' file in this directory.
2. Copy the code below and paste it into 'university_calender_quater-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./university_calender_quater.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUniversityid").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.universityCalenderQuater",
    options: {
        tableName: "university_calender_quater",
        //schema: "Rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "university_calender_quater_pkey"
        },
        "universityid": {
            type: Seq.INTEGER,
            field: "universityid",
            allowNull: false,
            references: "university",
            referencesKey: "universityid"
        },
        "year": {
            type: Seq.INTEGER,
            field: "year",
            allowNull: false
        },
        "fallquaterstartdate": {
            type: Seq.DATE,
            field: "fallquaterstartdate",
            allowNull: false
        },
        "fallquaterenddate": {
            type: Seq.DATE,
            field: "fallquaterenddate",
            allowNull: false
        },
        "winterquaterstartdate": {
            type: Seq.DATE,
            field: "winterquaterstartdate",
            allowNull: false
        },
        "winterquaterenddate": {
            type: Seq.DATE,
            field: "winterquaterenddate",
            allowNull: false
        },
        "springquaterstartdate": {
            type: Seq.DATE,
            field: "springquaterstartdate",
            allowNull: false
        },
        "springquaterenddate": {
            type: Seq.DATE,
            field: "springquaterenddate",
            allowNull: false
        },
        "summerquaterstartdate": {
            type: Seq.DATE,
            field: "summerquaterstartdate",
            allowNull: false
        },
        "summerquaterenddate": {
            type: Seq.DATE,
            field: "summerquaterenddate",
            allowNull: false
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.university",
        schema: "Rented",
        table: "university",
        source: "generator",
        details: {
            as: "relatedUniversityid",
            foreignKey: "universityid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
