/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'looking-custom.js' file in this directory.
2. Copy the code below and paste it into 'looking-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./looking.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.looking",
    options: {
        tableName: "looking",
        //schema: "Rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "looking_pkey"
        },
        "maxmonthlyrent": {
            type: Seq.INTEGER,
            field: "maxmonthlyrent",
            allowNull: false
        },
        "utilitiesincluded": {
            type: Seq.INTEGER,
            field: "utilitiesincluded",
            allowNull: false
        },
        "area": {
            type: Seq.STRING(30),
            field: "area"
        },
        "distancetouniv": {
            type: Seq.FLOAT(53),
            field: "distancetouniv"
        },
        "moveindate": {
            type: Seq.DATE,
            field: "moveindate",
            allowNull: false
        },
        "lengthofstay": {
            type: Seq.INTEGER,
            field: "lengthofstay"
        },
        "longtermintention": {
            type: Seq.INTEGER,
            field: "longtermintention"
        },
        "opentofullyearleasenewroomates": {
            type: Seq.INTEGER,
            field: "opentofullyearleasenewroomates"
        },
        "roomtype": {
            type: Seq.STRING(250),
            field: "roomtype"
        },
        "sharedbathroom": {
            type: Seq.INTEGER,
            field: "sharedbathroom"
        },
        "gender": {
            type: Seq.STRING(250),
            field: "gender",
            allowNull: false
        },
        "numroommates": {
            type: Seq.INTEGER,
            field: "numroommates"
        },
        "furnished": {
            type: Seq.INTEGER,
            field: "furnished"
        },
        "busrouterequired": {
            type: Seq.INTEGER,
            field: "busrouterequired"
        },
        "parkingneeded": {
            type: Seq.INTEGER,
            field: "parkingneeded"
        },
        "smokingallowed": {
            type: Seq.INTEGER,
            field: "smokingallowed"
        },
        "petsallowed": {
            type: Seq.INTEGER,
            field: "petsallowed"
        },
        "coupleallowed": {
            type: Seq.INTEGER,
            field: "coupleallowed"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: []
};
