/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'apartment_complex_floor_plan-custom.js' file in this directory.
2. Copy the code below and paste it into 'apartment_complex_floor_plan-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./apartment_complex_floor_plan.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedComplexId").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "apartmentComplexFloorPlan",
    options: {
        tableName: "apartment_complex_floor_plan",
   //     schema: "rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "apartment_complex_floor_plan_pkey"
        },
        "complexId": {
            type: Seq.BIGINT,
            field: "complexId",
            allowNull: false,
            references: "apartment_complex",
            referencesKey: "complexId"
        },
        "bedrooms": {
            type: Seq.BIGINT,
            field: "bedrooms",
            allowNull: false
        },
        "bathrooms": {
            type: Seq.BIGINT,
            field: "bathrooms",
            allowNull: false
        },
        "parking": {
            type: Seq.BIGINT,
            field: "parking",
            allowNull: false
        },
        "livingArea": {
            type: Seq.BIGINT,
            field: "living_area",
            allowNull: false
        },
        "washerDryer": {
            type: Seq.BOOLEAN,
            field: "washer_dryer",
            allowNull: false
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "apartmentComplex",
        schema: "rented",
        table: "apartment_complex",
        source: "generator",
        details: {
            as: "relatedComplexId",
            foreignKey: "complexId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
