/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'apartment_complex-custom.js' file in this directory.
2. Copy the code below and paste it into 'apartment_complex-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./apartment_complex.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("aptComplexFloorPlanComplexIds").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "apartmentComplex",
    options: {
        tableName: "apartment_complex",
   //     schema: "rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "apartment_complex_pkey"
        },
        "name": {
            type: Seq.STRING(255),
            field: "name",
            allowNull: false
        },
        "streetNumeric": {
            type: Seq.INTEGER,
            field: "streetNumeric",
            allowNull: false
        },
        "streetAddress": {
            type: Seq.STRING(255),
            field: "streetAddress",
            allowNull: false
        },
        "city": {
            type: Seq.STRING(30),
            field: "city",
            allowNull: false
        },
        "state": {
            type: Seq.STRING(2),
            field: "state",
            allowNull: false
        },
        "zip": {
            type: Seq.BIGINT,
            field: "zip",
            allowNull: false
        },
        "latitude": {
            type: Seq.DECIMAL(10, 8),
            field: "latitude"
        },
        "longitude": {
            type: Seq.DECIMAL(11, 8),
            field: "longitude"
        },
        "distanceToUniv": {
            type: Seq.FLOAT(53),
            field: "distanceToUniv"
        },
        "petsAllowed": {
            type: Seq.BOOLEAN,
            field: "petsAllowed",
            allowNull: false
        },
        "dogsAllowed": {
            type: Seq.BOOLEAN,
            field: "dogsAllowed",
            allowNull: false
        },
        "catsAllowed": {
            type: Seq.BOOLEAN,
            field: "catsAllowed",
            allowNull: false
        },
        "othersAllowed": {
            type: Seq.BOOLEAN,
            field: "othersAllowed",
            allowNull: false
        },
        "dogQtyAllowed": {
            type: Seq.BIGINT,
            field: "dogQtyAllowed"
        },
        "catQtyAllowed": {
            type: Seq.BIGINT,
            field: "catQtyAllowed"
        },
        "otherQtyAllowed": {
            type: Seq.BIGINT,
            field: "otherQtyAllowed"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "hasMany",
        model: "apartmentComplexFloorPlan",
        schema: "rented",
        table: "apartment_complex_floor_plan",
        source: "generator",
        details: {
            as: "aptComplexFloorPlanComplexIds",
            foreignKey: "complexId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "apartmentComplexImage",
        schema: "rented",
        table: "apartment_complex_image",
        source: "generator",
        details: {
            as: "aptComplexImageComplexIds",
            foreignKey: "complexId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "apartmentComplexTransportation",
        schema: "rented",
        table: "apartment_complex_transportation",
        source: "generator",
        details: {
            as: "aptComplexTransComplexIds",
            foreignKey: "complexId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
