/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'lessee-custom.js' file in this directory.
2. Copy the code below and paste it into 'lessee-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./lessee.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedLeaseId").onDelete = 'CASCADE';
util.getAttribute("leaseId").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "lessee",
    options: {
        tableName: "lessee",
    //    schema: "rented",
        timestamps: false
    },
    attributes: {
        "leaseId": {
            type: Seq.BIGINT,
            field: "leaseId",
            primaryKey: true,
            allowNull: false,
            unique: "lessee_pkey",
            references: "lease",
            referencesKey: "leaseId"
        },
        "userId": {
            type: Seq.BIGINT,
            field: "userId",
            primaryKey: true,
            allowNull: false,
            unique: "lessee_pkey",
            references: "rented_user",
            referencesKey: "userId"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "lease",
        schema: "rented",
        table: "lease",
        source: "generator",
        details: {
            as: "relatedLeaseId",
            foreignKey: "leaseId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rentedUser",
        schema: "rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserId",
            foreignKey: "userId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
