/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'looking-custom.js' file in this directory.
2. Copy the code below and paste it into 'looking-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./looking.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "looking",
    options: {
        tableName: "looking",
        //schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "idx_41737_PRIMARY"
        },
        "maxMonthlyRent": {
            type: Seq.INTEGER,
            field: "maxMonthlyRent",
            allowNull: false
        },
        "utilitiesIncluded": {
            type: Seq.BOOLEAN,
            field: "utilitiesIncluded",
            allowNull: false
        },
        "area": {
            type: Seq.TEXT,
            field: "area"
        },
        "distanceToUniv": {
            type: Seq.FLOAT(53),
            field: "distanceToUniv"
        },
        "moveInDate": {
            type: Seq.DATE,
            field: "moveInDate",
            allowNull: false
        },
        "moveOutDate": {
            type: Seq.DATE,
            field: "moveOutDate"
        },
        "lengthOfStay": {
            type: Seq.INTEGER,
            field: "lengthOfStay"
        },
        "openToFullYearLeaseNewRoomates": {
            type: Seq.BOOLEAN,
            field: "openToFullYearLeaseNewRoomates"
        },
        "roomType": {
            type: Seq.ENUM('single', 'double', 'living room'),
            field: "roomType"
        },
        "sharedBathroom": {
            type: Seq.BOOLEAN,
            field: "sharedBathroom"
        },
        "gender": {
            type: Seq.ENUM('no preference', 'male only', 'female only'),
            field: "gender",
            allowNull: false
        },
        "numRoommates": {
            type: Seq.INTEGER,
            field: "numRoommates"
        },
        "furnished": {
            type: Seq.BOOLEAN,
            field: "furnished"
        },
        "busRouteRequired": {
            type: Seq.BOOLEAN,
            field: "busRouteRequired"
        },
        "parkingNeeded": {
            type: Seq.BOOLEAN,
            field: "parkingNeeded"
        },
        "smokingAllowed": {
            type: Seq.BOOLEAN,
            field: "smokingAllowed"
        },
        "activeLooking": {
            type: Seq.BOOLEAN,
            field: "activeLooking",
            allowNull: false
        },
        "petsAllowed": {
            type: Seq.BOOLEAN,
            field: "petsAllowed"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        },
      "userId": {
        type: Seq.BIGINT,
        field: "userId",
        allowNull: false,
        references: "rented_user",
        referencesKey: "userId"
      }
    },
  relations: [{
    type: "belongsTo",
    model: "rentedUser",
    schema: "public",
    table: "rented_user",
    source: "generator",
    details: {
      as: "relatedUserId",
      foreignKey: "userId",
      onDelete: "NO ACTION",
      onUpdate: "NO ACTION"
    }
  }]
};
