/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'payment-custom.js' file in this directory.
2. Copy the code below and paste it into 'payment-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./payment.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedPayeeId").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "payment",
    options: {
        tableName: "payment",
        //schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "idx_41757_PRIMARY"
        },
        "payerId": {
            type: Seq.BIGINT,
            field: "payerId",
            allowNull: false,
            references: "rented_user",
            referencesKey: "payerId"
        },
        "payeeId": {
            type: Seq.BIGINT,
            field: "payeeId",
            allowNull: false,
            references: "rented_user",
            referencesKey: "payeeId"
        },
        "dollarAmount": {
            type: Seq.FLOAT(53),
            field: "dollarAmount"
        },
        "reason": {
            type: Seq.TEXT,
            field: "reason"
        },
        "rentPayment": {
            type: Seq.BOOLEAN,
            field: "rentPayment"
        },
        "creditCheckPayment": {
            type: Seq.BOOLEAN,
            field: "creditCheckPayment"
        },
        "paymentForm": {
            type: Seq.ENUM('"credit card"', 'ACH', 'cash'),
            field: "paymentForm"
        },
        "paymentDate": {
            type: Seq.DATE,
            field: "paymentDate",
            allowNull: false
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedPayeeId",
            foreignKey: "payeeId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedPayerId",
            foreignKey: "payerId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
