/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'property_lease_defaults-custom.js' file in this directory.
2. Copy the code below and paste it into 'property_lease_defaults-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./property_lease_defaults.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedOwnerId").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "propertyLeaseDefaults",
    options: {
        tableName: "property_lease_defaults",
        //schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "idx_41837_PRIMARY"
        },
        "propertyId": {
            type: Seq.BIGINT,
            field: "propertyId",
            allowNull: false,
            references: "property",
            referencesKey: "propertyId"
        },
        "ownerId": {
            type: Seq.BIGINT,
            field: "ownerId",
            allowNull: false,
            references: "rented_user",
            referencesKey: "ownerId"
        },
        "qtyDogsAllowed": {
            type: Seq.INTEGER,
            field: "qtyDogsAllowed",
            allowNull: false
        },
        "qtyCatsAllowed": {
            type: Seq.INTEGER,
            field: "qtyCatsAllowed",
            allowNull: false
        },
        "qtyOtherAllowed": {
            type: Seq.INTEGER,
            field: "qtyOtherAllowed",
            allowNull: false
        },
        "animalSizeLimitLbs": {
            type: Seq.INTEGER,
            field: "animalSizeLimitLbs",
            allowNull: false
        },
        "fishTankAllowed": {
            type: Seq.BOOLEAN,
            field: "fishTankAllowed",
            allowNull: false
        },
        "preferredLeaseLength": {
            type: Seq.INTEGER,
            field: "preferredLeaseLength",
            allowNull: false
        },
        "preferredLeaseUnit": {
            type: Seq.ENUM('day', 'week', 'month', 'year'),
            field: "preferredLeaseUnit",
            allowNull: false
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedOwnerId",
            foreignKey: "ownerId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "property",
        schema: "public",
        table: "property",
        source: "generator",
        details: {
            as: "relatedPropertyId",
            foreignKey: "propertyId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
