/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'property_ownership-custom.js' file in this directory.
2. Copy the code below and paste it into 'property_ownership-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./property_ownership.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("propertyOwnershipFKs").onDelete = 'CASCADE';
util.getAttribute("startDate").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "propertyOwnership",
    options: {
        tableName: "property_ownership",
        //schema: "public",
        timestamps: false
    },
    attributes: {
        "startDate": {
            type: Seq.DATE,
            field: "startDate",
            allowNull: false
        },
        "endDate": {
            type: Seq.DATE,
            field: "endDate",
            allowNull: false
        },
        "propertyFK": {
            type: Seq.BIGINT,
            field: "propertyFK",
            allowNull: false,
            references: "property",
            referencesKey: "propertyFK"
        },
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "idx_41924_PRIMARY"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "hasMany",
        model: "propertyOwner",
        schema: "public",
        table: "property_owner",
        source: "generator",
        details: {
            as: "propertyOwnershipFKs",
            foreignKey: "propertyOwnershipId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "property",
        schema: "public",
        table: "property",
        source: "generator",
        details: {
            as: "relatedPropertyFK",
            foreignKey: "propertyFK",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedPropertyOwnershipFKOwnerIds",
            foreignKey: "propertyOwnershipId",
            otherKey: "ownerId",
            through: "property_owner",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
