/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'pet-custom.js' file in this directory.
2. Copy the code below and paste it into 'pet-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./pet.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUserid").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.pet",
    options: {
        tableName: "pet",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "pet_pkey"
        },
        "userid": {
            type: Seq.INTEGER,
            field: "userid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "userid"
        },
        "type": {
            type: Seq.STRING(250),
            field: "type",
            allowNull: false
        },
        "breed": {
            type: Seq.STRING(45),
            field: "breed",
            allowNull: false
        },
        "weightlbs": {
            type: Seq.INTEGER,
            field: "weightlbs"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserid",
            foreignKey: "userid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};