/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'rental_applicant-custom.js' file in this directory.
2. Copy the code below and paste it into 'rental_applicant-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./rental_applicant.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedRentalappid").onDelete = 'CASCADE'; 
util.getAttribute("userid").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.rentalApplicant",
    options: {
        tableName: "rental_applicant",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "userid": {
            type: Seq.INTEGER,
            field: "userid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "userid"
        },
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "rental_applicant_pkey"
        },
        "rentalappid": {
            type: Seq.INTEGER,
            field: "rentalappid",
            allowNull: false,
            references: "rental_application",
            referencesKey: "rentalappid"
        },
        "sharecredit": {
            type: Seq.INTEGER,
            field: "sharecredit"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.rentalApplication",
        schema: "public",
        table: "rental_application",
        source: "generator",
        details: {
            as: "relatedRentalappid",
            foreignKey: "rentalappid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserid",
            foreignKey: "userid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};