/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'property_owner-custom.js' file in this directory.
2. Copy the code below and paste it into 'property_owner-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./property_owner.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedOwnerid").onDelete = 'CASCADE'; 
util.getAttribute("propertyownershipid").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.propertyOwner",
    options: {
        tableName: "property_owner",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "propertyownershipid": {
            type: Seq.INTEGER,
            field: "propertyownershipid",
            primaryKey: true,
            allowNull: false,
            unique: "property_owner_pkey",
            references: "property_ownership",
            referencesKey: "propertyownershipid"
        },
        "ownerid": {
            type: Seq.INTEGER,
            field: "ownerid",
            primaryKey: true,
            allowNull: false,
            unique: "property_owner_pkey",
            references: "rented_user",
            referencesKey: "ownerid"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedOwnerid",
            foreignKey: "ownerid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.propertyOwnership",
        schema: "public",
        table: "property_ownership",
        source: "generator",
        details: {
            as: "relatedPropertyownershipid",
            foreignKey: "propertyownershipid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};