/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'student-custom.js' file in this directory.
2. Copy the code below and paste it into 'student-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./student.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("firstname").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.student",
    options: {
        tableName: "student",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "firstname": {
            type: Seq.STRING(30),
            field: "firstname",
            allowNull: false
        },
        "lastname": {
            type: Seq.STRING(30),
            field: "lastname",
            allowNull: false
        },
        "email": {
            type: Seq.STRING(60),
            field: "email"
        },
        "street": {
            type: Seq.STRING(50),
            field: "street",
            allowNull: false
        },
        "city": {
            type: Seq.STRING(40),
            field: "city",
            allowNull: false
        }
    },
    relations: []
};