/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'apartment_complex_floor_plan-custom.js' file in this directory.
2. Copy the code below and paste it into 'apartment_complex_floor_plan-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./apartment_complex_floor_plan.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedComplexid").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.apartmentComplexFloorPlan",
    options: {
        tableName: "apartment_complex_floor_plan",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "apartment_complex_floor_plan_pkey"
        },
        "complexid": {
            type: Seq.INTEGER,
            field: "complexid",
            allowNull: false,
            references: "apartment_complex",
            referencesKey: "complexid"
        },
        "bedrooms": {
            type: Seq.INTEGER,
            field: "bedrooms",
            allowNull: false
        },
        "bathrooms": {
            type: Seq.INTEGER,
            field: "bathrooms",
            allowNull: false
        },
        "parking": {
            type: Seq.INTEGER,
            field: "parking",
            allowNull: false
        },
        "livingArea": {
            type: Seq.INTEGER,
            field: "living_area",
            allowNull: false
        },
        "washerDryer": {
            type: Seq.INTEGER,
            field: "washer_dryer",
            allowNull: false
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.apartmentComplex",
        schema: "public",
        table: "apartment_complex",
        source: "generator",
        details: {
            as: "relatedComplexid",
            foreignKey: "complexid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};