/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'payment-custom.js' file in this directory.
2. Copy the code below and paste it into 'payment-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./payment.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedPayeeid").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.payment",
    options: {
        tableName: "payment",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "payment_pkey"
        },
        "payerid": {
            type: Seq.INTEGER,
            field: "payerid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "payerid"
        },
        "payeeid": {
            type: Seq.INTEGER,
            field: "payeeid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "payeeid"
        },
        "dollaramount": {
            type: Seq.FLOAT(53),
            field: "dollaramount"
        },
        "reason": {
            type: Seq.STRING(255),
            field: "reason"
        },
        "rentpayment": {
            type: Seq.INTEGER,
            field: "rentpayment"
        },
        "creditcheckpayment": {
            type: Seq.INTEGER,
            field: "creditcheckpayment"
        },
        "paymentform": {
            type: Seq.STRING(250),
            field: "paymentform"
        },
        "paymentdate": {
            type: Seq.DATE,
            field: "paymentdate",
            allowNull: false
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedPayeeid",
            foreignKey: "payeeid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedPayerid",
            foreignKey: "payerid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};