/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'lease-custom.js' file in this directory.
2. Copy the code below and paste it into 'lease-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./lease.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("lesseeLeaseidFkeys").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.lease",
    options: {
        tableName: "lease",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "lease_pkey"
        },
        "propertyid": {
            type: Seq.INTEGER,
            field: "propertyid",
            allowNull: false,
            references: "property",
            referencesKey: "propertyid"
        },
        "approved": {
            type: Seq.INTEGER,
            field: "approved"
        },
        "startdate": {
            type: Seq.DATE,
            field: "startdate",
            allowNull: false
        },
        "enddate": {
            type: Seq.DATE,
            field: "enddate",
            allowNull: false
        },
        "paymentamount": {
            type: Seq.FLOAT(53),
            field: "paymentamount",
            allowNull: false
        },
        "paymentinterval": {
            type: Seq.STRING(250),
            field: "paymentinterval",
            allowNull: false
        },
        "securitydeposit": {
            type: Seq.FLOAT(53),
            field: "securitydeposit"
        },
        "petdeposit": {
            type: Seq.FLOAT(53),
            field: "petdeposit"
        },
        "payee": {
            type: Seq.STRING(45),
            field: "payee"
        },
        "built": {
            type: Seq.DATE,
            field: "built"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.lessee",
        schema: "public",
        table: "lessee",
        source: "generator",
        details: {
            as: "lesseeLeaseidFkeys",
            foreignKey: "leaseid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.property",
        schema: "public",
        table: "property",
        source: "generator",
        details: {
            as: "relatedPropertyid",
            foreignKey: "propertyid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedLesseeLeaseidFkeyUserids",
            foreignKey: "leaseid",
            otherKey: "userid",
            through: "lessee",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};