/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'property_ownership-custom.js' file in this directory.
2. Copy the code below and paste it into 'property_ownership-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./property_ownership.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("propertyOwnerPropertyownershipidFkeys").onDelete = 'CASCADE'; 
util.getAttribute("startdate").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.propertyOwnership",
    options: {
        tableName: "property_ownership",
        schema: "Rented",
        timestamps: false
    },
    attributes: {
        "startdate": {
            type: Seq.DATE,
            field: "startdate",
            allowNull: false
        },
        "enddate": {
            type: Seq.DATE,
            field: "enddate",
            allowNull: false
        },
        "propertyfk": {
            type: Seq.INTEGER,
            field: "propertyfk",
            allowNull: false,
            references: "property",
            referencesKey: "propertyfk"
        },
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "property_ownership_pkey"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "hasMany",
        model: "rented.propertyOwner",
        schema: "Rented",
        table: "property_owner",
        source: "generator",
        details: {
            as: "propertyOwnerPropertyownershipidFkeys",
            foreignKey: "propertyownershipid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rented.property",
        schema: "Rented",
        table: "property",
        source: "generator",
        details: {
            as: "relatedPropertyfk",
            foreignKey: "propertyfk",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedPropertyOwnerPropertyownershipidFkeyOwnerids",
            foreignKey: "propertyownershipid",
            otherKey: "ownerid",
            through: "property_owner",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};