/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'rental_application-custom.js' file in this directory.
2. Copy the code below and paste it into 'rental_application-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./rental_application.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("rentalApplicantRentalappidFkeys").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.rentalApplication",
    options: {
        tableName: "rental_application",
        schema: "Rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "rental_application_pkey"
        },
        "propertyid": {
            type: Seq.INTEGER,
            field: "propertyid",
            allowNull: false,
            references: "property",
            referencesKey: "propertyid"
        },
        "preferredleaselength": {
            type: Seq.INTEGER,
            field: "preferredleaselength"
        },
        "preferredmovein": {
            type: Seq.DATE,
            field: "preferredmovein",
            allowNull: false
        },
        "numoccupants": {
            type: Seq.INTEGER,
            field: "numoccupants",
            allowNull: false
        },
        "movereason": {
            type: Seq.STRING(255),
            field: "movereason"
        },
        "preferredleaselengthunit": {
            type: Seq.STRING(250),
            field: "preferredleaselengthunit"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "hasMany",
        model: "rented.rentalApplicant",
        schema: "Rented",
        table: "rental_applicant",
        source: "generator",
        details: {
            as: "rentalApplicantRentalappidFkeys",
            foreignKey: "rentalappid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rented.property",
        schema: "Rented",
        table: "property",
        source: "generator",
        details: {
            as: "relatedPropertyid",
            foreignKey: "propertyid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedRentalApplicantRentalappidFkeyUserids",
            foreignKey: "rentalappid",
            otherKey: "userid",
            through: "rental_applicant",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};