/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'rental_application-custom.js' file in this directory.
2. Copy the code below and paste it into 'rental_application-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./rental_application.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("rentalAppIds").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rentalApplication",
    options: {
        tableName: "rental_application",
        //schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "idx_41949_id_UNIQUE"
        },
        "propertyId": {
            type: Seq.BIGINT,
            field: "propertyId",
            allowNull: false,
            references: "property",
            referencesKey: "propertyId"
        },
        "preferredLeaseLength": {
            type: Seq.INTEGER,
            field: "preferredLeaseLength"
        },
        "preferredMoveIn": {
            type: Seq.DATE,
            field: "preferredMoveIn",
            allowNull: false
        },
        "numOccupants": {
            type: Seq.BIGINT,
            field: "numOccupants",
            allowNull: false
        },
        "moveReason": {
            type: Seq.TEXT,
            field: "moveReason"
        },
        "preferredLeaseLengthUnit": {
            type: Seq.ENUM('day', 'week', 'month', 'year'),
            field: "preferredLeaseLengthUnit"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "hasMany",
        model: "rentalApplicant",
        schema: "public",
        table: "rental_applicant",
        source: "generator",
        details: {
            as: "rentalAppIds",
            foreignKey: "rentalAppId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "property",
        schema: "public",
        table: "property",
        source: "generator",
        details: {
            as: "relatedPropertyId",
            foreignKey: "propertyId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedRentalAppIdUserIds",
            foreignKey: "rentalAppId",
            otherKey: "userId",
            through: "rental_applicant",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
