/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'university_calender_semester-custom.js' file in this directory.
2. Copy the code below and paste it into 'university_calender_semester-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./university_calender_semester.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUniversityId").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.universityCalenderSemester",
    options: {
        tableName: "university_calender_semester",
        //schema: "rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "university_calender_semester_pkey"
        },
        "universityId": {
            type: Seq.BIGINT,
            field: "universityId",
            allowNull: false,
            references: "university",
            referencesKey: "universityId"
        },
        "year": {
            type: Seq.INTEGER,
            field: "year",
            allowNull: false
        },
        "fallSemesterStartDate": {
            type: Seq.DATE,
            field: "fallSemesterStartDate",
            allowNull: false
        },
        "fallSemesterEndDate": {
            type: Seq.DATE,
            field: "fallSemesterEndDate",
            allowNull: false
        },
        "springSemesterStartDate": {
            type: Seq.DATE,
            field: "springSemesterStartDate",
            allowNull: false
        },
        "springSemesterEndDate": {
            type: Seq.DATE,
            field: "springSemesterEndDate",
            allowNull: false
        },
        "summerSemesterStartDate": {
            type: Seq.DATE,
            field: "summerSemesterStartDate",
            allowNull: false
        },
        "summerSemesterEndDate": {
            type: Seq.DATE,
            field: "summerSemesterEndDate",
            allowNull: false
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.university",
        schema: "rented",
        table: "university",
        source: "generator",
        details: {
            as: "relatedUniversityId",
            foreignKey: "universityId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};