/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'lessee-custom.js' file in this directory.
2. Copy the code below and paste it into 'lessee-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./lessee.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedLeaseid").onDelete = 'CASCADE'; 
util.getAttribute("leaseid").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.lessee",
    options: {
        tableName: "lessee",
        schema: "Rented",
        timestamps: false
    },
    attributes: {
        "leaseid": {
            type: Seq.INTEGER,
            field: "leaseid",
            allowNull: false,
            unique: "lessee_pkey",
            references: "lease",
            referencesKey: "leaseid"
        },
        "userid": {
            type: Seq.INTEGER,
            field: "userid",
            allowNull: false,
            unique: "lessee_pkey",
            references: "rented_user",
            referencesKey: "userid"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.lease",
        schema: "Rented",
        table: "lease",
        source: "generator",
        details: {
            as: "relatedLeaseid",
            foreignKey: "leaseid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserid",
            foreignKey: "userid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};