/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'room_listing_view-custom.js' file in this directory.
2. Copy the code below and paste it into 'room_listing_view-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./room_listing_view.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("streetnumeric").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.roomListingView",
    options: {
        tableName: "room_listing_view",
        schema: "Rented",
        timestamps: false
    },
    attributes: {
        "streetnumeric": {
            type: Seq.INTEGER,
            field: "streetnumeric"
        },
        "streetaddress": {
            type: Seq.STRING(255),
            field: "streetaddress"
        },
        "city": {
            type: Seq.STRING(30),
            field: "city"
        },
        "state": {
            type: Seq.STRING(2),
            field: "state"
        },
        "zip": {
            type: Seq.INTEGER,
            field: "zip"
        },
        "apt": {
            type: Seq.STRING(6),
            field: "apt"
        },
        "bldg": {
            type: Seq.STRING(10),
            field: "bldg"
        },
        "type": {
            type: Seq.STRING(250),
            field: "type"
        },
        "bedrooms": {
            type: Seq.INTEGER,
            field: "bedrooms"
        },
        "bathrooms": {
            type: Seq.INTEGER,
            field: "bathrooms"
        },
        "id": {
            type: Seq.INTEGER,
            field: "id"
        },
        "propertyid": {
            type: Seq.INTEGER,
            field: "propertyid"
        },
        "creatorid": {
            type: Seq.INTEGER,
            field: "creatorid"
        },
        "monthlyprice": {
            type: Seq.FLOAT(53),
            field: "monthlyprice"
        },
        "securitydeposit": {
            type: Seq.FLOAT(53),
            field: "securitydeposit"
        },
        "availablemovein": {
            type: Seq.DATE,
            field: "availablemovein"
        },
        "leaseenddate": {
            type: Seq.DATE,
            field: "leaseenddate"
        },
        "leasetype": {
            type: Seq.STRING(250),
            field: "leasetype"
        },
        "gender": {
            type: Seq.STRING(250),
            field: "gender"
        },
        "monthlyutilitycost": {
            type: Seq.INTEGER,
            field: "monthlyutilitycost"
        },
        "roomtype": {
            type: Seq.STRING(250),
            field: "roomtype"
        },
        "sharedbathroom": {
            type: Seq.INTEGER,
            field: "sharedbathroom"
        },
        "numroomates": {
            type: Seq.INTEGER,
            field: "numroomates"
        },
        "furnished": {
            type: Seq.INTEGER,
            field: "furnished"
        },
        "parkingavailable": {
            type: Seq.INTEGER,
            field: "parkingavailable"
        },
        "smokingallowed": {
            type: Seq.INTEGER,
            field: "smokingallowed"
        },
        "description": {
            type: Seq.STRING(255),
            field: "description"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat"
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: []
};