/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'user_recommendation-custom.js' file in this directory.
2. Copy the code below and paste it into 'user_recommendation-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./user_recommendation.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedRecommendedid").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.userRecommendation",
    options: {
        tableName: "user_recommendation",
        schema: "Rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "user_recommendation_pkey"
        },
        "recommendedid": {
            type: Seq.INTEGER,
            field: "recommendedid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "recommendedid"
        },
        "recommendorid": {
            type: Seq.INTEGER,
            field: "recommendorid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "recommendorid"
        },
        "recommendedapproved": {
            type: Seq.INTEGER,
            field: "recommendedapproved",
            allowNull: false
        },
        "content": {
            type: Seq.STRING(255),
            field: "content"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedRecommendedid",
            foreignKey: "recommendedid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedRecommendorid",
            foreignKey: "recommendorid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};