/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'university_calender_semester-custom.js' file in this directory.
2. Copy the code below and paste it into 'university_calender_semester-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./university_calender_semester.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUniversityid").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.universityCalenderSemester",
    options: {
        tableName: "university_calender_semester",
        schema: "Rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "university_calender_semester_pkey"
        },
        "universityid": {
            type: Seq.INTEGER,
            field: "universityid",
            allowNull: false,
            references: "university",
            referencesKey: "universityid"
        },
        "year": {
            type: Seq.INTEGER,
            field: "year",
            allowNull: false
        },
        "fallsemesterstartdate": {
            type: Seq.DATE,
            field: "fallsemesterstartdate",
            allowNull: false
        },
        "fallsemesterenddate": {
            type: Seq.DATE,
            field: "fallsemesterenddate",
            allowNull: false
        },
        "springsemesterstartdate": {
            type: Seq.DATE,
            field: "springsemesterstartdate",
            allowNull: false
        },
        "springsemesterenddate": {
            type: Seq.DATE,
            field: "springsemesterenddate",
            allowNull: false
        },
        "summersemesterstartdate": {
            type: Seq.DATE,
            field: "summersemesterstartdate",
            allowNull: false
        },
        "summersemesterenddate": {
            type: Seq.DATE,
            field: "summersemesterenddate",
            allowNull: false
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.university",
        schema: "Rented",
        table: "university",
        source: "generator",
        details: {
            as: "relatedUniversityid",
            foreignKey: "universityid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};