/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'address_history-custom.js' file in this directory.
2. Copy the code below and paste it into 'address_history-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./address_history.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUserid").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.addressHistory",
    options: {
        tableName: "address_history",
        schema: "Rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "address_history_pkey"
        },
        "streetnumeric": {
            type: Seq.INTEGER,
            field: "streetnumeric",
            allowNull: false
        },
        "streetaddress": {
            type: Seq.STRING(255),
            field: "streetaddress",
            allowNull: false
        },
        "apt": {
            type: Seq.STRING(6),
            field: "apt"
        },
        "city": {
            type: Seq.STRING(30),
            field: "city",
            allowNull: false
        },
        "state": {
            type: Seq.STRING(2),
            field: "state",
            allowNull: false
        },
        "zip": {
            type: Seq.INTEGER,
            field: "zip",
            allowNull: false
        },
        "startdate": {
            type: Seq.DATE,
            field: "startdate",
            allowNull: false
        },
        "enddate": {
            type: Seq.DATE,
            field: "enddate"
        },
        "userid": {
            type: Seq.INTEGER,
            field: "userid",
            references: "rented_user",
            referencesKey: "userid"
        },
        "aboutme": {
            type: Seq.STRING(255),
            field: "aboutme"
        },
        "present": {
            type: Seq.INTEGER,
            field: "present"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserid",
            foreignKey: "userid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};