/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'user_reference-custom.js' file in this directory.
2. Copy the code below and paste it into 'user_reference-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./user_reference.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUserid").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.userReference",
    options: {
        tableName: "user_reference",
        schema: "Rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "user_reference_pkey"
        },
        "userid": {
            type: Seq.INTEGER,
            field: "userid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "userid"
        },
        "email": {
            type: Seq.STRING(255),
            field: "email",
            allowNull: false
        },
        "phone": {
            type: Seq.INTEGER,
            field: "phone",
            allowNull: false
        },
        "firstname": {
            type: Seq.STRING(45),
            field: "firstname",
            allowNull: false
        },
        "lastname": {
            type: Seq.STRING(45),
            field: "lastname",
            allowNull: false
        },
        "relation": {
            type: Seq.STRING(250),
            field: "relation",
            allowNull: false
        },
        "startdate": {
            type: Seq.DATE,
            field: "startdate",
            allowNull: false
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserid",
            foreignKey: "userid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};