/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'user_reference-custom.js' file in this directory.
2. Copy the code below and paste it into 'user_reference-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./user_reference.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUserId").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.userReference",
    options: {
        tableName: "user_reference",
        //schema: "rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "user_reference_pkey"
        },
        "userId": {
            type: Seq.BIGINT,
            field: "userId",
            allowNull: false,
            references: "rented_user",
            referencesKey: "userId"
        },
        "email": {
            type: Seq.STRING(255),
            field: "email",
            allowNull: false
        },
        "phone": {
            type: Seq.INTEGER,
            field: "phone",
            allowNull: false
        },
        "firstName": {
            type: Seq.STRING(45),
            field: "firstName",
            allowNull: false
        },
        "lastName": {
            type: Seq.STRING(45),
            field: "lastName",
            allowNull: false
        },
        "relation": {
            type: Seq.CHAR(255),
            field: "relation",
            allowNull: false
        },
        "startDate": {
            type: Seq.DATE,
            field: "startDate",
            allowNull: false
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserId",
            foreignKey: "userId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};