/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'user_cosigner-custom.js' file in this directory.
2. Copy the code below and paste it into 'user_cosigner-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./user_cosigner.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedCosginerid").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.userCosigner",
    options: {
        tableName: "user_cosigner",
        schema: "Rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "user_cosigner_pkey"
        },
        "cosingeeid": {
            type: Seq.INTEGER,
            field: "cosingeeid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "cosingeeid"
        },
        "cosginerid": {
            type: Seq.INTEGER,
            field: "cosginerid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "cosginerid"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedCosginerid",
            foreignKey: "cosginerid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedCosingeeid",
            foreignKey: "cosingeeid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};