/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'property_likes-custom.js' file in this directory.
2. Copy the code below and paste it into 'property_likes-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./property_likes.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedPropertyid").onDelete = 'CASCADE'; 
util.getAttribute("propertyid").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "rented.propertyLikes",
    options: {
        tableName: "property_likes",
        schema: "Rented",
        timestamps: false
    },
    attributes: {
        "propertyid": {
            type: Seq.INTEGER,
            field: "propertyid",
            allowNull: false,
            references: "property",
            referencesKey: "propertyid"
        },
        "userid": {
            type: Seq.INTEGER,
            field: "userid",
            allowNull: false,
            references: "rented_user",
            referencesKey: "userid"
        },
        "id": {
            type: Seq.INTEGER,
            field: "id",
            allowNull: false,
            unique: "property_likes_pkey"
        },
        "createdat": {
            type: Seq.DATE,
            field: "createdat",
            allowNull: false
        },
        "updatedat": {
            type: Seq.DATE,
            field: "updatedat"
        },
        "deletedat": {
            type: Seq.DATE,
            field: "deletedat"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rented.property",
        schema: "Rented",
        table: "property",
        source: "generator",
        details: {
            as: "relatedPropertyid",
            foreignKey: "propertyid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rented.rentedUser",
        schema: "Rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserid",
            foreignKey: "userid",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};