/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'user_cosigner-custom.js' file in this directory.
2. Copy the code below and paste it into 'user_cosigner-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./user_cosigner.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedCosginerId").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "userCosigner",
    options: {
        tableName: "user_cosigner",
        //schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "idx_42056_PRIMARY"
        },
        "cosingeeId": {
            type: Seq.BIGINT,
            field: "cosingeeId",
            allowNull: false,
            references: "rented_user",
            referencesKey: "cosingeeId"
        },
        "cosginerId": {
            type: Seq.BIGINT,
            field: "cosginerId",
            allowNull: false,
            references: "rented_user",
            referencesKey: "cosginerId"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedCosginerId",
            foreignKey: "cosginerId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedCosingeeId",
            foreignKey: "cosingeeId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
