/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'user_cur_address_univ_coords-custom.js' file in this directory.
2. Copy the code below and paste it into 'user_cur_address_univ_coords-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models/index.js'),
    model   = require('./user_cur_address_univ_coords.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("userId").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "userCurAddressUnivCoords",
    options: {
        tableName: "user_cur_address_univ_coords",
      //  schema: "public",
        timestamps: false
    },
    attributes: {
        "userId": {
            type: Seq.BIGINT,
            field: "userId"
        },
        "addressLatitude": {
            type: Seq.DECIMAL(10, 8),
            field: "address_latitude"
        },
        "addressLongitude": {
            type: Seq.DECIMAL(11, 8),
            field: "address_longitude"
        },
        "univLatitude": {
            type: Seq.DECIMAL(10, 8),
            field: "univ_latitude"
        },
        "univLongitude": {
            type: Seq.DECIMAL(11, 8),
            field: "univ_longitude"
        },
        "univName": {
            type: Seq.TEXT,
            field: "univ_name"
        }
    },
    relations: []
};
