/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'user_education-custom.js' file in this directory.
2. Copy the code below and paste it into 'user_education-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('temp_models/index.js'),
    model   = require('./user_education.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUniversityId").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "userEducation",
    options: {
        tableName: "user_education",
    //    schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "idx_42081_PRIMARY"
        },
        "userId": {
            type: Seq.BIGINT,
            field: "userId",
            allowNull: false,
            references: "rented_user",
            referencesKey: "userId"
        },
        "educationCenterName": {
            type: Seq.TEXT,
            field: "educationCenterName",
            allowNull: false
        },
        "type": {
            type: Seq.ENUM('university', 'trade', 'military'),
            field: "type"
        },
        "startDate": {
            type: Seq.DATE,
            field: "startDate"
        },
        "endDate": {
            type: Seq.DATE,
            field: "endDate"
        },
        "graduation": {
            type: Seq.BOOLEAN,
            field: "graduation"
        },
        "graduationDate": {
            type: Seq.DATE,
            field: "graduationDate"
        },
        "major": {
            type: Seq.TEXT,
            field: "major"
        },
        "degreeType": {
            type: Seq.ENUM('undergraduate', 'graduate', 'doctorate', 'post-doctorate'),
            field: "degreeType"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        },
        "universityId": {
            type: Seq.BIGINT,
            field: "universityId",
            allowNull: false,
            references: "university",
            referencesKey: "universityId"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "university",
        schema: "public",
        table: "university",
        source: "generator",
        details: {
            as: "relatedUniversityId",
            foreignKey: "universityId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "rentedUser",
        schema: "public",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserId",
            foreignKey: "userId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
