/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'user_financial-custom.js' file in this directory.
2. Copy the code below and paste it into 'user_financial-custom.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./user_financial.js'),
    util    = require('./utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedUserId").onDelete = 'CASCADE';
util.getAttribute("id").comment = 'This is the comment';

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "userFinancial",
    options: {
        tableName: "user_financial",
      //  schema: "rented",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "user_financial_pkey"
        },
        "userId": {
            type: Seq.BIGINT,
            field: "userId",
            allowNull: false,
            references: "rented_user",
            referencesKey: "userId"
        },
        "startDate": {
            type: Seq.DATE,
            field: "startDate",
            allowNull: false
        },
        "endDate": {
            type: Seq.DATE,
            field: "endDate"
        },
        "individualAnnualIncom": {
            type: Seq.BIGINT,
            field: "individualAnnualIncom"
        },
        "householdAnnualIncome": {
            type: Seq.BIGINT,
            field: "householdAnnualIncome"
        },
        "spouseAnnualIncome": {
            type: Seq.BIGINT,
            field: "spouseAnnualIncome"
        },
        "incomeProof": {
            type: Seq.STRING(255),
            field: "incomeProof"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt"
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deletedAt"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "rentedUser",
        schema: "rented",
        table: "rented_user",
        source: "generator",
        details: {
            as: "relatedUserId",
            foreignKey: "userId",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};
