var path = require('path');

module.exports = {
  "sequelize-pg-generator": {
    "database": {
      "host": "127.0.0.1",
      "port": 5432,
      "user": "postgres", //your username (postgres is default), in pgAdmin right click on DB > properties, in owner field
      "password": "password", //your password
      "database": "rented",   // lets keep it lowercase rented
      "schema": ["rented"]
    },
    "output": {
      "log": true,
      "folder": "./models",
      "beautify": true,
      "indent": 4,
      "preserveNewLines": false,
      "warning": true
    },
    "generate": {
      "stripFirstTableFromHasMany": true,
      "addTableNameToManyToMany": false,
      "addRelationNameToManyToMany": true,
      "stripFirstTableNameFromManyToMany": true,
      "hasManyThrough": false,
      "belongsToMany": true,
      "prefixForBelongsTo": "related",
      "useSchemaName": false,
    //  "modelCamelCase": true,
   //   "relationAccessorCamelCase": true, //we don't need extra flags for uppercase, because they are generated by default if using windows converted
   //   "columnAccessorCamelCase": true,
      "columnDefault": false,
      "columnDescription": true,
      "columnAutoIncrement": true,
      "tableDescription": true,
      "dataTypeVariable": "Seq",
      "skipTable": []
    },
    "tableOptions": {
      "timestamps": false
    }
  }
};
